"""
EMA + Alarm score simulation — SCENARIO injected from device.

Fetched : 2026-04-11T20:27:09
Source  : http://192.168.10.2
Records : 55

Run:
    python tests/sim_20260411_202709.py
"""

import sys
from pathlib import Path

# Locate docs/ relative to this file so sim1 is importable regardless of cwd
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "docs"))
import sim1

# ═══════════════════════════════════════════════════════════════════
#  CONFIGURATION — copied from device at fetch time
# ═══════════════════════════════════════════════════════════════════

INITIAL_EMA  = 200.2287   # back-calculated EMA before oldest record
ALPHA        = 0.2
CLAMP        = 0.4

ZONE_GREEN   = 40
ZONE_YELLOW  = 200

P1 = 0.2
P2 = 0.8

# ═══════════════════════════════════════════════════════════════════
#  SCENARIO — fetched from device (oldest → newest)
# ═══════════════════════════════════════════════════════════════════

SCENARIO = [
    0.00, 262.20, 145.45, 190.98, 140.90, 167.44, 157.69, 188.68, 203.16, 140.96,
    127.39, 235.45, 115.16, 172.50, 151.01, 144.75, 145.75, 177.25, 136.36, 127.52,
    114.43, 55.73, 109.09, 73.25, 237.62, 155.44, 35.78, 1153.85, 278.64, 429.08,
    251.57, 281.25, 287.08, 233.46, 237.00, 179.91, 253.16, 160.64, 309.01, 185.47,
    220.86, 241.29, 219.51, 218.98, 224.72, 251.05, 38.03, 68.87, 21.49, 99.53,
    389.19, 188.98, 227.85, 131.58, 121.66,
]

FLOW_RATES = SCENARIO

# ═══════════════════════════════════════════════════════════════════
#  DATA INSPECTION — raw device snapshot
# ═══════════════════════════════════════════════════════════════════

_RAW = {   'alg': {   'alarm_p1': 0.2,
               'alarm_p2': 0.8,
               'ema_alpha': 0.2,
               'ema_clamp': 0.4,
               'initial_ema': 200,
               'success': True,
               'zone_green': 40,
               'zone_yellow': 200},
    'cycles': [   {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 54,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 20,
                      'interval_s': 2959,
                      'manual': False,
                      'rate_ml_h': 121.6627,
                      'red_alert': False,
                      'ts': 1775931845},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 53,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 19,
                      'interval_s': 2736,
                      'manual': False,
                      'rate_ml_h': 131.5789,
                      'red_alert': False,
                      'ts': 1775928886},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 52,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 18,
                      'interval_s': 1580,
                      'manual': False,
                      'rate_ml_h': 227.8481,
                      'red_alert': False,
                      'ts': 1775926150},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 51,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 18,
                      'interval_s': 1905,
                      'manual': False,
                      'rate_ml_h': 188.9764,
                      'red_alert': False,
                      'ts': 1775924570},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 50,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 925,
                      'manual': False,
                      'rate_ml_h': 389.1892,
                      'red_alert': False,
                      'ts': 1775922665},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 49,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 17,
                      'interval_s': 3617,
                      'manual': False,
                      'rate_ml_h': 99.53,
                      'red_alert': False,
                      'ts': 1775921740},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 48,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 16,
                      'interval_s': 16753,
                      'manual': False,
                      'rate_ml_h': 21.48869,
                      'red_alert': False,
                      'ts': 1775918123},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 47,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 11,
                      'interval_s': 5227,
                      'manual': False,
                      'rate_ml_h': 68.87316,
                      'red_alert': False,
                      'ts': 1775901370},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 46,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 10,
                      'interval_s': 9466,
                      'manual': False,
                      'rate_ml_h': 38.03085,
                      'red_alert': False,
                      'ts': 1775896143},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 45,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 7,
                      'interval_s': 1434,
                      'manual': False,
                      'rate_ml_h': 251.046,
                      'red_alert': False,
                      'ts': 1775886677},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 44,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 7,
                      'interval_s': 1602,
                      'manual': False,
                      'rate_ml_h': 224.7191,
                      'red_alert': False,
                      'ts': 1775885243},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 43,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 7,
                      'interval_s': 1644,
                      'manual': False,
                      'rate_ml_h': 218.9781,
                      'red_alert': False,
                      'ts': 1775883641},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 42,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 6,
                      'interval_s': 1640,
                      'manual': False,
                      'rate_ml_h': 219.5122,
                      'red_alert': False,
                      'ts': 1775881997},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 41,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 6,
                      'interval_s': 1492,
                      'manual': False,
                      'rate_ml_h': 241.2868,
                      'red_alert': False,
                      'ts': 1775880357},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 40,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 5,
                      'interval_s': 1630,
                      'manual': False,
                      'rate_ml_h': 220.8589,
                      'red_alert': False,
                      'ts': 1775878865},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 39,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 5,
                      'interval_s': 1941,
                      'manual': False,
                      'rate_ml_h': 185.4714,
                      'red_alert': False,
                      'ts': 1775877235},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 38,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 4,
                      'interval_s': 1165,
                      'manual': False,
                      'rate_ml_h': 309.0129,
                      'red_alert': False,
                      'ts': 1775875294},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 37,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 4,
                      'interval_s': 2241,
                      'manual': False,
                      'rate_ml_h': 160.6426,
                      'red_alert': False,
                      'ts': 1775874129},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 36,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 3,
                      'interval_s': 1422,
                      'manual': False,
                      'rate_ml_h': 253.1646,
                      'red_alert': False,
                      'ts': 1775871888},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 35,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 3,
                      'interval_s': 2001,
                      'manual': False,
                      'rate_ml_h': 179.91,
                      'red_alert': False,
                      'ts': 1775870466},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 34,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 2,
                      'interval_s': 1519,
                      'manual': False,
                      'rate_ml_h': 236.998,
                      'red_alert': False,
                      'ts': 1775868465},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 33,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 2,
                      'interval_s': 1542,
                      'manual': False,
                      'rate_ml_h': 233.463,
                      'red_alert': False,
                      'ts': 1775866946},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 32,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 1254,
                      'manual': False,
                      'rate_ml_h': 287.0813,
                      'red_alert': False,
                      'ts': 1775865404},
                  {   'alert': 1,
                      'bootstrap': False,
                      'cycle': 31,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 1280,
                      'manual': False,
                      'rate_ml_h': 281.25,
                      'red_alert': False,
                      'ts': 1775864150},
                  {   'alert': 1,
                      'bootstrap': False,
                      'cycle': 30,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 1,
                      'interval_s': 1431,
                      'manual': False,
                      'rate_ml_h': 251.5723,
                      'red_alert': False,
                      'ts': 1775862870},
                  {   'alert': 1,
                      'bootstrap': False,
                      'cycle': 29,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 839,
                      'manual': False,
                      'rate_ml_h': 429.0822,
                      'red_alert': False,
                      'ts': 1775861439},
                  {   'alert': 1,
                      'bootstrap': False,
                      'cycle': 28,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 1292,
                      'manual': False,
                      'rate_ml_h': 278.6378,
                      'red_alert': False,
                      'ts': 1775860600},
                  {   'alert': 1,
                      'bootstrap': False,
                      'cycle': 27,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 312,
                      'manual': False,
                      'rate_ml_h': 1153.846,
                      'red_alert': False,
                      'ts': 1775859308},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 26,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 0,
                      'interval_s': 10061,
                      'manual': False,
                      'rate_ml_h': 35.78173,
                      'red_alert': False,
                      'ts': 1775858996},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 25,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 21,
                      'interval_s': 2316,
                      'manual': False,
                      'rate_ml_h': 155.4404,
                      'red_alert': False,
                      'ts': 1775848935},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 24,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 20,
                      'interval_s': 1515,
                      'manual': False,
                      'rate_ml_h': 237.6238,
                      'red_alert': False,
                      'ts': 1775846619},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 23,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 20,
                      'interval_s': 4915,
                      'manual': False,
                      'rate_ml_h': 73.24517,
                      'red_alert': False,
                      'ts': 1775845104},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 22,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 18,
                      'interval_s': 3300,
                      'manual': False,
                      'rate_ml_h': 109.0909,
                      'red_alert': False,
                      'ts': 1775840189},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 21,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 18,
                      'interval_s': 6460,
                      'manual': False,
                      'rate_ml_h': 55.72755,
                      'red_alert': False,
                      'ts': 1775836889},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 20,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 16,
                      'interval_s': 3146,
                      'manual': False,
                      'rate_ml_h': 114.431,
                      'red_alert': False,
                      'ts': 1775830429},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 19,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 15,
                      'interval_s': 2823,
                      'manual': False,
                      'rate_ml_h': 127.5239,
                      'red_alert': False,
                      'ts': 1775827283},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 18,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 14,
                      'interval_s': 2640,
                      'manual': False,
                      'rate_ml_h': 136.3636,
                      'red_alert': False,
                      'ts': 1775824460},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 17,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 13,
                      'interval_s': 2031,
                      'manual': False,
                      'rate_ml_h': 177.2526,
                      'red_alert': False,
                      'ts': 1775821820},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 16,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 13,
                      'interval_s': 2470,
                      'manual': False,
                      'rate_ml_h': 145.749,
                      'red_alert': False,
                      'ts': 1775819789},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 15,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 12,
                      'interval_s': 2487,
                      'manual': False,
                      'rate_ml_h': 144.7527,
                      'red_alert': False,
                      'ts': 1775817319},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 14,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 11,
                      'interval_s': 2384,
                      'manual': False,
                      'rate_ml_h': 151.0067,
                      'red_alert': False,
                      'ts': 1775814832},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 13,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 11,
                      'interval_s': 2087,
                      'manual': False,
                      'rate_ml_h': 172.4964,
                      'red_alert': False,
                      'ts': 1775812448},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 12,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 10,
                      'interval_s': 3126,
                      'manual': False,
                      'rate_ml_h': 115.1632,
                      'red_alert': False,
                      'ts': 1775810361},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 11,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 9,
                      'interval_s': 1529,
                      'manual': False,
                      'rate_ml_h': 235.448,
                      'red_alert': False,
                      'ts': 1775807235},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 10,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 9,
                      'interval_s': 2826,
                      'manual': False,
                      'rate_ml_h': 127.3885,
                      'red_alert': False,
                      'ts': 1775805706},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 9,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 8,
                      'interval_s': 2554,
                      'manual': False,
                      'rate_ml_h': 140.9554,
                      'red_alert': False,
                      'ts': 1775802880},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 8,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 7,
                      'interval_s': 1772,
                      'manual': False,
                      'rate_ml_h': 203.1603,
                      'red_alert': False,
                      'ts': 1775800326},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 7,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 7,
                      'interval_s': 1908,
                      'manual': False,
                      'rate_ml_h': 188.6792,
                      'red_alert': False,
                      'ts': 1775798554},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 6,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 6,
                      'interval_s': 2283,
                      'manual': False,
                      'rate_ml_h': 157.6873,
                      'red_alert': False,
                      'ts': 1775796646},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 5,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 6,
                      'interval_s': 2150,
                      'manual': False,
                      'rate_ml_h': 167.4419,
                      'red_alert': False,
                      'ts': 1775794363},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 4,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 5,
                      'interval_s': 2555,
                      'manual': False,
                      'rate_ml_h': 140.9002,
                      'red_alert': False,
                      'ts': 1775792213},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 3,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 4,
                      'interval_s': 1885,
                      'manual': False,
                      'rate_ml_h': 190.9814,
                      'red_alert': False,
                      'ts': 1775789658},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 2,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 4,
                      'interval_s': 2475,
                      'manual': False,
                      'rate_ml_h': 145.4545,
                      'red_alert': False,
                      'ts': 1775787773},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 1,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 3,
                      'interval_s': 1373,
                      'manual': False,
                      'rate_ml_h': 262.1996,
                      'red_alert': False,
                      'ts': 1775785298},
                  {   'alert': 0,
                      'bootstrap': False,
                      'cycle': 0,
                      'daily_lim': False,
                      'dev_sigma': 0,
                      'hour': 3,
                      'interval_s': 0,
                      'manual': False,
                      'rate_ml_h': 0,
                      'red_alert': False,
                      'ts': 1775783925}],
    'ema_rate_now': 165.6712,
    'fetched_at': '2026-04-11T20:27:09',
    'initial_ema': 200.2286781782923,
    'record_count': 55,
    'source': 'http://192.168.10.2'}


def print_raw():
    """Print the raw device snapshot for inspection."""
    SEP = "─" * 76
    print()
    print(SEP)
    print("  RAW DEVICE SNAPSHOT")
    print(SEP)
    print(f"  Fetched at     : {_RAW['fetched_at']}")
    print(f"  Source         : {_RAW['source']}")
    print(f"  EMA on device  : {_RAW['ema_rate_now']:.2f} ml/h")
    print(f"  EMA₀ back-calc : {_RAW['initial_ema']:.4f} ml/h  "
          f"(EMA before oldest buffered record)")
    print(f"  Records        : {_RAW['record_count']}")
    print()
    print(f"  {' #':>4}  {' timestamp':^20}  {'rate_ml_h':>10}"
          f"  {'interval_s':>10}  {'alert':>5}  {'cycle':>5}")
    print(f"  {'-'*62}")
    for i, rec in enumerate(_RAW['cycles']):
        print(
            f"  {i:>4}  {str(rec.get('ts','?')):^20}"
            f"  {rec.get('rate_ml_h', 0):>10.2f}"
            f"  {rec.get('interval_s', 0):>10.1f}"
            f"  {rec.get('alert', 0):>5}"
            f"  {rec.get('cycle', 0):>5}"
        )
    print(SEP)
    print()


# ═══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    # 1. Show raw data
    print_raw()

    # 2. Patch sim1 zone globals so zone() colouring matches device settings
    sim1.ZONE_GREEN  = ZONE_GREEN
    sim1.ZONE_YELLOW = ZONE_YELLOW

    # 3. Run simulation
    rows = sim1.simulate(FLOW_RATES, INITIAL_EMA, ALPHA, CLAMP, P1, P2)
    sim1.print_table(rows, INITIAL_EMA, ALPHA, CLAMP, P1, P2)
